server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://host.docker.internal:5432/schooldb
    url: jdbc:postgresql://postgres_db:5432/schooldb
    username: cosmind
    password:
school:
  dataprovider:
    url: http://externalschool:8081
